from __future__ import annotations

from typing import Any, Protocol


class TargetAdapter(Protocol):
    async def discover_schema(self) -> dict[str, Any]: ...
    async def lookup(self, employee_id: str | None = None, email: str | None = None) -> dict[str, Any] | None: ...
    async def create(self, payload: dict[str, Any], idempotency_key: str) -> dict[str, Any]: ...
    async def update(self, target_id: str, payload: dict[str, Any], idempotency_key: str) -> dict[str, Any]: ...
    async def verify(self, target_id: str) -> dict[str, Any]: ...
    async def rollback(self, target_id: str, before: dict[str, Any] | None, operation: str) -> dict[str, Any]: ...

