from __future__ import annotations

from pathlib import Path
from typing import Any

import pandas as pd
from app.db.mongo import MemoryStore, MongoStore
from app.models.records import FileProfile

ALLOWED_EXTENSIONS = {".csv", ".xlsx"}


class FileService:
    def __init__(self, store: MemoryStore | MongoStore, max_upload_mb: int, upload_dir: str = "uploads") -> None:
        self.store = store
        self.max_bytes = max_upload_mb * 1024 * 1024
        self.upload_dir = Path(upload_dir)
        self.upload_dir.mkdir(parents=True, exist_ok=True)

    def _validate_name(self, filename: str) -> Path:
        name = Path(filename or "upload.csv").name
        if Path(name).suffix.lower() not in ALLOWED_EXTENSIONS:
            raise ValueError("Only CSV and XLSX files are supported")
        return Path(name)

    async def save_upload(self, migration_id: str, tenant_id: str, filename: str, content: bytes) -> dict[str, Any]:
        safe_name = self._validate_name(filename)
        if len(content) > self.max_bytes:
            raise ValueError(f"File exceeds {self.max_bytes // (1024 * 1024)} MB limit")
        target_dir = self.upload_dir / migration_id
        target_dir.mkdir(parents=True, exist_ok=True)
        path = target_dir / safe_name
        path.write_bytes(content)
        profile, rows = self.read_file(path)
        doc = {
            "tenant_id": tenant_id,
            "migration_id": migration_id,
            "file_name": safe_name.name,
            "path": str(path),
            "file_type": path.suffix.lower().lstrip("."),
            "profile": profile.model_dump(),
            "rows": rows,
        }
        return await self.store.insert("files", doc)

    def read_file(self, path: Path) -> tuple[FileProfile, list[dict[str, Any]]]:
        if path.suffix.lower() == ".csv":
            frame = pd.read_csv(path, dtype=str, keep_default_na=False)
        else:
            frame = pd.read_excel(path, dtype=str).fillna("")
        frame.columns = [str(column).strip() for column in frame.columns]
        rows = [{str(key): ("" if pd.isna(value) else str(value)) for key, value in row.items()} for row in frame.to_dict(orient="records")]
        profile = self.profile(path.name, path.suffix.lower().lstrip("."), frame, rows)
        return profile, rows

    @staticmethod
    def profile(file_name: str, file_type: str, frame: pd.DataFrame, rows: list[dict[str, Any]]) -> FileProfile:
        columns: dict[str, dict[str, Any]] = {}
        for column in frame.columns:
            values = [str(value).strip() for value in frame[column].tolist() if str(value).strip()]
            sample = values[:5]
            kind = "string"
            if values and all(value.isdigit() for value in values):
                kind = "integer"
            elif values and any("@" in value for value in values):
                kind = "email"
            elif values and any("/" in value or "-" in value for value in values):
                kind = "date_or_string"
            columns[str(column)] = {"inferred_type": kind, "non_empty": len(values), "sample": sample}
        key_candidates = [column for column in frame.columns if any(token in str(column).lower() for token in ("id", "email", "employee"))]
        return FileProfile(file_name=file_name, file_type=file_type, row_count=len(rows), headers=[str(c) for c in frame.columns], columns=columns, entity_key_candidates=[str(c) for c in key_candidates])

    async def load_sample(self, migration_id: str, tenant_id: str, sample_dir: str) -> list[dict[str, Any]]:
        directory = Path(sample_dir)
        if not directory.exists():
            raise FileNotFoundError(f"Sample directory not found: {directory}")
        docs: list[dict[str, Any]] = []
        # CSVs are always present in source control; the legacy XLSX is generated by sample_data/generate_samples.py when needed.
        for path in sorted(directory.iterdir()):
            if path.suffix.lower() not in ALLOWED_EXTENSIONS:
                continue
            profile, rows = self.read_file(path)
            docs.append(await self.store.insert("files", {"tenant_id": tenant_id, "migration_id": migration_id, "file_name": path.name, "path": str(path), "file_type": path.suffix.lower().lstrip("."), "profile": profile.model_dump(), "rows": rows, "sample": True}))
        return docs

