/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as IndexRouteImport } from './routes/index'
import { Route as AgentPoliciesRouteImport } from './routes/agent-policies'
import { Route as AuditLogRouteImport } from './routes/audit-log'
import { Route as EscalationsRouteImport } from './routes/escalations'
import { Route as ExecutionRouteImport } from './routes/execution'
import { Route as MappingStudioRouteImport } from './routes/mapping-studio'
import { Route as MigrationsRouteImport } from './routes/migrations'
import { Route as SettingsRouteImport } from './routes/settings'
import { Route as TargetSystemsRouteImport } from './routes/target-systems'
import { Route as MigrationsMigrationIdRouteImport } from './routes/migrations.$migrationId'

const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const AgentPoliciesRoute = AgentPoliciesRouteImport.update({
  id: '/agent-policies',
  path: '/agent-policies',
  getParentRoute: () => rootRouteImport,
} as any)
const AuditLogRoute = AuditLogRouteImport.update({
  id: '/audit-log',
  path: '/audit-log',
  getParentRoute: () => rootRouteImport,
} as any)
const EscalationsRoute = EscalationsRouteImport.update({
  id: '/escalations',
  path: '/escalations',
  getParentRoute: () => rootRouteImport,
} as any)
const ExecutionRoute = ExecutionRouteImport.update({
  id: '/execution',
  path: '/execution',
  getParentRoute: () => rootRouteImport,
} as any)
const MappingStudioRoute = MappingStudioRouteImport.update({
  id: '/mapping-studio',
  path: '/mapping-studio',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsRoute = MigrationsRouteImport.update({
  id: '/migrations',
  path: '/migrations',
  getParentRoute: () => rootRouteImport,
} as any)
const SettingsRoute = SettingsRouteImport.update({
  id: '/settings',
  path: '/settings',
  getParentRoute: () => rootRouteImport,
} as any)
const TargetSystemsRoute = TargetSystemsRouteImport.update({
  id: '/target-systems',
  path: '/target-systems',
  getParentRoute: () => rootRouteImport,
} as any)
const MigrationsMigrationIdRoute = MigrationsMigrationIdRouteImport.update({
  id: '/$migrationId',
  path: '/$migrationId',
  getParentRoute: () => MigrationsRoute,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/agent-policies': typeof AgentPoliciesRoute
  '/audit-log': typeof AuditLogRoute
  '/escalations': typeof EscalationsRoute
  '/execution': typeof ExecutionRoute
  '/mapping-studio': typeof MappingStudioRoute
  '/migrations': typeof MigrationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/target-systems': typeof TargetSystemsRoute
  '/migrations/$migrationId': typeof MigrationsMigrationIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/agent-policies': typeof AgentPoliciesRoute
  '/audit-log': typeof AuditLogRoute
  '/escalations': typeof EscalationsRoute
  '/execution': typeof ExecutionRoute
  '/mapping-studio': typeof MappingStudioRoute
  '/migrations': typeof MigrationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/target-systems': typeof TargetSystemsRoute
  '/migrations/$migrationId': typeof MigrationsMigrationIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/agent-policies': typeof AgentPoliciesRoute
  '/audit-log': typeof AuditLogRoute
  '/escalations': typeof EscalationsRoute
  '/execution': typeof ExecutionRoute
  '/mapping-studio': typeof MappingStudioRoute
  '/migrations': typeof MigrationsRouteWithChildren
  '/settings': typeof SettingsRoute
  '/target-systems': typeof TargetSystemsRoute
  '/migrations/$migrationId': typeof MigrationsMigrationIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/agent-policies'
    | '/audit-log'
    | '/escalations'
    | '/execution'
    | '/mapping-studio'
    | '/migrations'
    | '/settings'
    | '/target-systems'
    | '/migrations/$migrationId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/agent-policies'
    | '/audit-log'
    | '/escalations'
    | '/execution'
    | '/mapping-studio'
    | '/migrations'
    | '/settings'
    | '/target-systems'
    | '/migrations/$migrationId'
  id:
    | '__root__'
    | '/'
    | '/agent-policies'
    | '/audit-log'
    | '/escalations'
    | '/execution'
    | '/mapping-studio'
    | '/migrations'
    | '/settings'
    | '/target-systems'
    | '/migrations/$migrationId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AgentPoliciesRoute: typeof AgentPoliciesRoute
  AuditLogRoute: typeof AuditLogRoute
  EscalationsRoute: typeof EscalationsRoute
  ExecutionRoute: typeof ExecutionRoute
  MappingStudioRoute: typeof MappingStudioRoute
  MigrationsRoute: typeof MigrationsRouteWithChildren
  SettingsRoute: typeof SettingsRoute
  TargetSystemsRoute: typeof TargetSystemsRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/agent-policies': {
      id: '/agent-policies'
      path: '/agent-policies'
      fullPath: '/agent-policies'
      preLoaderRoute: typeof AgentPoliciesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/audit-log': {
      id: '/audit-log'
      path: '/audit-log'
      fullPath: '/audit-log'
      preLoaderRoute: typeof AuditLogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/escalations': {
      id: '/escalations'
      path: '/escalations'
      fullPath: '/escalations'
      preLoaderRoute: typeof EscalationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/execution': {
      id: '/execution'
      path: '/execution'
      fullPath: '/execution'
      preLoaderRoute: typeof ExecutionRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/mapping-studio': {
      id: '/mapping-studio'
      path: '/mapping-studio'
      fullPath: '/mapping-studio'
      preLoaderRoute: typeof MappingStudioRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations': {
      id: '/migrations'
      path: '/migrations'
      fullPath: '/migrations'
      preLoaderRoute: typeof MigrationsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/settings': {
      id: '/settings'
      path: '/settings'
      fullPath: '/settings'
      preLoaderRoute: typeof SettingsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/target-systems': {
      id: '/target-systems'
      path: '/target-systems'
      fullPath: '/target-systems'
      preLoaderRoute: typeof TargetSystemsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/migrations/$migrationId': {
      id: '/migrations/$migrationId'
      path: '/$migrationId'
      fullPath: '/migrations/$migrationId'
      preLoaderRoute: typeof MigrationsMigrationIdRouteImport
      parentRoute: typeof MigrationsRoute
    }
  }
}

interface MigrationsRouteChildren {
  MigrationsMigrationIdRoute: typeof MigrationsMigrationIdRoute
}

const MigrationsRouteChildren: MigrationsRouteChildren = {
  MigrationsMigrationIdRoute: MigrationsMigrationIdRoute,
}

const MigrationsRouteWithChildren = MigrationsRoute._addFileChildren(
  MigrationsRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AgentPoliciesRoute: AgentPoliciesRoute,
  AuditLogRoute: AuditLogRoute,
  EscalationsRoute: EscalationsRoute,
  ExecutionRoute: ExecutionRoute,
  MappingStudioRoute: MappingStudioRoute,
  MigrationsRoute: MigrationsRouteWithChildren,
  SettingsRoute: SettingsRoute,
  TargetSystemsRoute: TargetSystemsRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { startInstance } from './start.ts'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
    config: Awaited<ReturnType<typeof startInstance.getOptions>>
  }
}
